name: TulAdmin
main: org.tulonsae.mc.plugins.TulAdmin
version: ${project.version}

commands:
  genmap:
    aliases:
    description: Generates a map.  Type defaults to block.
    usage: |
        /<command> world:worldname [type:block|chunk|region] radius:number[;x,z]
        /<command> world:worldname [type:block|chunk|region] pos:x,z
        /<command> world:worldname [type:block|chunk|region] start:x,z end:x,z
