name: TulAdmin
main: org.tulonsae.mc.plugins.TulAdmin
version: ${project.version}

commands:
  genmap:
    aliases: [newreg]
    description: Generates a map.
    usage: |
        /<command> world:worldname [type:region] radius:number[;x,z]
        /<command> world:worldname [type:region] pos:x,z
        /<command> world:worldname [type:region] start:x,z end:x,z
