name: TulAdmin
main: org.tulonsae.mc.plugins.TulAdmin
version: 0.1-dev

commands:
  makevoidregion:
    aliases: [mkvoidreg, createvoidregion]
    description: Creates a void region in your current world.
    usage: |
        /<command> x z [ n | s | e | w | nw | ne | se | sw ]
           x   region x coordinate
           z   region z coordinate 
           n   create bedrock wall on north side of region
           s   create bedrock wall on south side of region
           e   create bedrock wall on east side of region
           w   create bedrock wall on west side of region
           nw  create bedrock column in northwest corner of region
           ne  create bedrock column in northeast corner of region
           se  create bedrock column in southeast corner of region
           sw  create bedrock column in southwest corner of region
